#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Final report generation + best-code export.

Refactored out of run_cellscientist.py.

Notable behavior:
- Outputs are saved under: results/${dataset_name}/finall_results/ (OR logs_dir/finall_results)
- The final report is generated by an LLM using `llm_report` (preferred) or
  fallback `llm` in pipeline_config.json.
- The LLM client uses a robust OpenAI-compatible HTTP call (requests) with
  retry/backoff.
"""

from __future__ import annotations

import json
import os
import re
import textwrap
import time
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import requests

try:
    import yaml
except Exception:
    yaml = None

from .config import deep_merge, drop_none
from .utils import (
    export_notebook_as_py,
    read_head_tail_lines,
    read_text,
    read_text_limited,
    safe_copy,
    safe_read_json,
    project_root,
)


FINAL_REPORT_DIRNAME = "finall_results"  # keep user's requested spelling
FINAL_REPORT_PROMPT_PATH = os.path.join(project_root(), "prompts", "final_report.yaml")


def redact_secrets(obj: Any) -> Any:
    """Best-effort redact API keys / tokens from configs before sending to LLM."""
    try:
        if isinstance(obj, dict):
            out = {}
            for k, v in obj.items():
                lk = str(k).lower()
                if any(x in lk for x in ["api_key", "apikey", "token", "secret", "password"]):
                    out[k] = "<redacted>"
                else:
                    out[k] = redact_secrets(v)
            return out
        if isinstance(obj, list):
            return [redact_secrets(x) for x in obj]
        if isinstance(obj, str) and (obj.startswith("sk-") or obj.startswith("Bearer ")):
            return "<redacted>"
    except Exception:
        return obj
    return obj


def ensure_final_prompt_file_exists() -> None:
    """Create a default final report prompt file if missing (non-destructive)."""
    p = Path(FINAL_REPORT_PROMPT_PATH)
    if p.exists():
        return
    try:
        p.parent.mkdir(parents=True, exist_ok=True)
        default_yaml = textwrap.dedent(
            """\
            system: |
                You are a senior Research Engineer + Computational Biologist.
                You will read the provided: `experiment_report.md` for Experiment/Review stages,
                pipeline/stage logs, and `pipeline_summary.json`, and generate a final Markdown analysis report.
                Writing Requirements:
                - Only output the Markdown body; do not output YAML/JSON/explanatory introductions.
                - Must cover and explicitly write out:
                1) Task definition and breakdown (what each sub-stage does, what the inputs/outputs are)
                2) Data path, runtime environment, key engineering parameters (GPU/CPU, CUDA_VISIBLE_DEVICES, hyperparameters, etc.)
                3) Experimental exploration process details: the effect of each run/iteration in each sub-stage (success/failure), triggered fixes, key changes
                4) Iteration reflection: why these changes were made, what was learned from failures, what to do next
                5) Final results: best metrics, best solution description, reproduction steps, key file paths

                Suggested output structure (can be fine-tuned, but must be complete):

                - Summary (1-2 paragraphs)
                - Pipeline overview (Experiment and Review stages)
                - Task definition and data/environment
                - Experiment Stage: Generate-Execute-Analyze (iteratively)
                - Review Stage: Optimize-Feedback (iteratively)
                - Best results and code saving instructions
                - Failure Cases and Reflections (if any)
                - Appendix: Critical Path List

            user_template: |
               # Input Materials (Please digest and write the final report; do not copy verbatim)

              ## 0) Meta
              dataset_name: ${dataset_name}
              report_output_dir: ${final_output_dir}

              ## 1) Pipeline Summary (json)
              ```json
              ${pipeline_summary_json}
              ```

              ## 2) Stage configs (redacted)
              ### Experiment config
              ```json
              ${experiment_config_json}
              ```

              ### Review config
              ```json
              ${review_config_json}
              ```

              ## 3) Experiment stage best experiment_report.md (if any)
              ```markdown
              ${experiment_report_md}
              ```

              ## 4) Review stage experiment_report.md (if any)
              ```markdown
              ${review_report_md}
              ```

              ## 5) Review stage optimization history (if any)
              ```markdown
              ${review_optim_history_md}
              ```

              ## 6) Iteration tables (machine extracted)
              ### Experiment iterations
              ```json
              ${experiment_iters_json}
              ```

              ### Review iterations
              ```json
              ${review_iters_json}
              ```

              ## 7) Logs (head+tail excerpts)
              ### pipeline log excerpt
              ```text
              ${pipeline_log_excerpt}
              ```

              ### experiment log excerpt
              ```text
              ${experiment_log_excerpt}
              ```

              ### review log excerpt
              ```text
              ${review_log_excerpt}
              ```
            """
        )
        p.write_text(default_yaml, encoding="utf-8")
    except Exception as e:
        print(f"[WARN] Failed to create default final report prompt file: {e}")


def load_final_prompt() -> Tuple[str, str]:
    ensure_final_prompt_file_exists()
    if yaml is None:
        return ("You are a scientific report writer. Output Markdown only.", "${pipeline_summary_json}")
    try:
        data = yaml.safe_load(Path(FINAL_REPORT_PROMPT_PATH).read_text(encoding="utf-8")) or {}
        system = str(data.get("system") or "").strip()
        user_t = str(data.get("user_template") or "").strip()
        if not system or not user_t:
            raise ValueError("final_report.yaml missing required fields")
        return system, user_t
    except Exception as e:
        print(f"[WARN] Failed to load final_report.yaml ({FINAL_REPORT_PROMPT_PATH}): {e}")
        return ("You are a scientific report writer. Output Markdown only.", "${pipeline_summary_json}")


# =============================================================================
# LLM client (robust) - OpenAI compatible
# =============================================================================


def resolve_report_llm_cfg(pipe_cfg: Optional[Dict[str, Any]]) -> Dict[str, Any]:
    """Resolve the report-only LLM config.

    Precedence:
      1) pipeline_config.llm_report (preferred)
      2) pipeline_config.llm (fallback)
      3) env vars

    Also supports api_key_env.
    """

    base_llm_raw = (pipe_cfg or {}).get("llm") if isinstance((pipe_cfg or {}).get("llm"), dict) else {}
    report_llm_raw = (pipe_cfg or {}).get("llm_report") if isinstance((pipe_cfg or {}).get("llm_report"), dict) else {}

    base_llm = drop_none(base_llm_raw) if isinstance(base_llm_raw, dict) else {}
    report_llm = drop_none(report_llm_raw) if isinstance(report_llm_raw, dict) else {}
    llm = deep_merge(base_llm, report_llm) if report_llm else base_llm

    base_url = llm.get("base_url") or os.environ.get("OPENAI_BASE_URL") or "https://api.openai.com/v1"
    model = llm.get("model") or os.environ.get("OPENAI_MODEL") or "gpt-4o-mini"

    api_key = llm.get("api_key")
    if not api_key:
        api_key_env = llm.get("api_key_env") or "OPENAI_API_KEY"
        api_key = os.environ.get(api_key_env)

    temperature = llm.get("temperature")
    temperature = 0.2 if temperature is None else float(temperature)

    max_tokens = llm.get("max_tokens")
    max_tokens = 8192 if max_tokens is None else int(max_tokens)

    timeout = llm.get("timeout")
    timeout = 600 if timeout is None else int(timeout)

    return {
        "base_url": str(base_url).rstrip("/"),
        "model": model,
        "api_key": api_key,
        "temperature": temperature,
        "max_tokens": max_tokens,
        "timeout": timeout,
    }


def _post_request(url: str, headers: Dict[str, str], payload: Dict[str, Any], timeout: int, retries: int = 3) -> Dict[str, Any]:
    last_err: Optional[Exception] = None
    for i in range(retries + 1):
        try:
            r = requests.post(url, headers=headers, json=payload, timeout=timeout)
            if r.status_code == 200:
                return r.json()

            # retry on typical transient failures
            if r.status_code in {408, 409, 429, 500, 502, 503, 504}:
                time.sleep(1.0 + 0.8 * i)
                continue

            # non-retriable: include small excerpt
            txt = (r.text or "").strip()
            raise RuntimeError(f"LLM HTTP {r.status_code}: {txt[:800]}")
        except Exception as e:
            last_err = e
            time.sleep(1.0 + 0.8 * i)
    raise RuntimeError(f"LLM request failed after {retries} retries. Last error: {last_err}")


def chat_text(messages: List[Dict[str, Any]], llm_cfg: Dict[str, Any]) -> str:
    if not llm_cfg.get("api_key"):
        raise RuntimeError("Missing API key for report generation. Use llm_report.api_key_env or OPENAI_API_KEY.")

    url = llm_cfg["base_url"].rstrip("/") + "/chat/completions"
    headers = {
        "Authorization": f"Bearer {llm_cfg['api_key']}",
        "Content-Type": "application/json",
    }
    payload = {
        "model": llm_cfg["model"],
        "messages": messages,
        "temperature": float(llm_cfg.get("temperature", 0.2)),
        "max_tokens": int(llm_cfg.get("max_tokens", 8192)),
        "stream": False,
    }

    data = _post_request(url, headers, payload, int(llm_cfg.get("timeout", 600)))
    try:
        content = data["choices"][0]["message"]["content"]
        return (content or "").strip()
    except Exception:
        return ""


# =============================================================================
# Selecting best runs + iteration extraction
# =============================================================================


def experiment_iters_detail_from_log(log_text: str, metric: str) -> List[Dict[str, Any]]:
    iters: Dict[int, Dict[str, Any]] = {}
    cur_iter: Optional[int] = None
    bug_markers = [
        "Notebook Generation Failed",
        "LLM_GEN_FAILURE",
        "CRITICAL PARSE FAILURE",
        "[GRAPH] ❌",
        "Error in Node",
        "Initiating Adaptive Fix",
        "[FIX]",
        "Traceback",
        "Exception:",
    ]

    for ln in (log_text or "").splitlines():
        m = re.search(r"ITERATION\s+(\d+)/(\d+)", ln)
        if m:
            cur_iter = int(m.group(1))
            iters.setdefault(cur_iter, {"iter": cur_iter, "bug": False, "score": None, "notes": []})
            continue

        if cur_iter is None:
            continue

        rec = iters.setdefault(cur_iter, {"iter": cur_iter, "bug": False, "score": None, "notes": []})

        if any(x in ln for x in bug_markers):
            rec["bug"] = True

        mm = re.search(rf"\[CHECK\].*?\b{re.escape(metric)}\s*:\s*([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)", ln)
        if mm:
            try:
                rec["score"] = float(mm.group(1))
            except Exception:
                pass

        if "prompt_run_" in ln or "Saved" in ln or "SUCCESS" in ln or "FAIL" in ln:
            if len(rec["notes"]) < 6:
                rec["notes"].append(ln.strip())

    return [iters[k] for k in sorted(iters.keys())]


def review_iters_from_history_state(workspace_dir: str) -> List[Dict[str, Any]]:
    p = os.path.join(workspace_dir, "history_state.json")
    hist = safe_read_json(p)
    if not isinstance(hist, list):
        return []
    out = []
    for rec in hist:
        if not isinstance(rec, dict):
            continue
        out.append(
            {
                "iter": rec.get("iter"),
                "decision": rec.get("decision"),
                "focus": rec.get("focus"),
                "strategy": rec.get("strategy"),
                "status": rec.get("status"),
                "score": rec.get("score"),
                "reflection": rec.get("reflection"),
                "semantic_gradient": rec.get("semantic_gradient"),
                "tasks": rec.get("task_names") or rec.get("tasks"),
            }
        )
    return out


# =============================================================================
# Main entry: generate final report
# =============================================================================


def generate_final_report(
    *,
    ds_name: str,
    results_root: str,
    pipeline_summary: Dict[str, Any],
    stage1_cfg: Dict[str, Any],
    stage2_cfg: Dict[str, Any],
    stage3_cfg: Dict[str, Any],
    stage_timings: Dict[str, Dict[str, float]],
    phase_logs: Dict[str, str],
    pipeline_log_path: str,
    pipe_cfg: Optional[Dict[str, Any]],
    # [NEW] Explicit path arguments to replace search functions
    explicit_experiment_path: Optional[str] = None,
    explicit_review_path: Optional[str] = None,
    direction: str,
    metric: str,
    output_dir: Optional[str] = None, # [NEW] Added to allow overriding output location (e.g. to logs_dir)
) -> Optional[str]:
    """Generate final_analysis_report.md and export best code to results/${dataset}/finall_results/."""

    # [FIX] Logic updated to use output_dir if present
    base_dest = output_dir if output_dir else results_root
    final_dir = os.path.join(base_dest, FINAL_REPORT_DIRNAME)
    os.makedirs(final_dir, exist_ok=True)
    
    print(f"📝 Generating Final Report in: {final_dir}")

    # Locate key artifacts
    # Keep placeholder variables for prompt compatibility, but leave content empty.
    phase1_summary_path = ""

    # [FIX] Use explicit paths instead of searching based on time
    best_exp_dir = explicit_experiment_path
    if best_exp_dir and not os.path.exists(best_exp_dir):
        # Fallback only if provided path is bad (shouldn't happen with log tracker)
        print(f"[WARN] Explicit Experiment path provided but not found: {best_exp_dir}")
        best_exp_dir = None
        
    experiment_report_path = os.path.join(best_exp_dir, "experiment_report.md") if best_exp_dir else ""

    review_ws = explicit_review_path
    if review_ws and not os.path.exists(review_ws):
        print(f"[WARN] Explicit Review path provided but not found: {review_ws}")
        review_ws = None
        
    review_report_path = os.path.join(review_ws, "experiment_report.md") if review_ws else ""
    review_opt_hist_path = os.path.join(review_ws, "optimization_history.md") if review_ws else ""

    # Export best code
    best_nb_src = ""
    # Priority: Review Best -> Experiment Executed -> Experiment Prompt
    if review_ws and os.path.exists(os.path.join(review_ws, "notebook_best.ipynb")):
        best_nb_src = os.path.join(review_ws, "notebook_best.ipynb")
    elif best_exp_dir and os.path.exists(os.path.join(best_exp_dir, "notebook_prompt_exec.ipynb")):
        best_nb_src = os.path.join(best_exp_dir, "notebook_prompt_exec.ipynb")
    elif best_exp_dir and os.path.exists(os.path.join(best_exp_dir, "notebook_prompt.ipynb")):
        best_nb_src = os.path.join(best_exp_dir, "notebook_prompt.ipynb")

    best_nb_dst = safe_copy(best_nb_src, final_dir, "best_code.ipynb") if best_nb_src else None
    if best_nb_dst:
        export_notebook_as_py(best_nb_dst, os.path.join(final_dir, "best_code.py"))

    # Also copy key inputs for convenience
    
    if best_exp_dir:
        safe_copy(os.path.join(best_exp_dir, "metrics.json"), final_dir, "experiment_best_metrics.json")
        safe_copy(experiment_report_path, final_dir, "experiment_best_experiment_report.md")
        
    if review_ws:
        safe_copy(os.path.join(review_ws, "metrics_best.json"), final_dir, "review_best_metrics.json")
        safe_copy(review_report_path, final_dir, "review_experiment_report.md")
        safe_copy(review_opt_hist_path, final_dir, "review_optimization_history.md")
        safe_copy(os.path.join(review_ws, "history_state.json"), final_dir, "review_history_state.json")
        
    safe_copy(pipeline_log_path, final_dir, os.path.basename(pipeline_log_path))
    for _k, lp in (phase_logs or {}).items():
        safe_copy(lp, final_dir, os.path.basename(lp))

    # Build iteration tables
    exp_log_text = read_text(phase_logs.get("Experiment", ""))
    exp_iters = experiment_iters_detail_from_log(exp_log_text, metric)
    review_iters = review_iters_from_history_state(review_ws) if review_ws else []

    system_prompt, user_template = load_final_prompt()
    llm_cfg = resolve_report_llm_cfg(pipe_cfg)

    pipeline_summary_json = json.dumps(redact_secrets(pipeline_summary), ensure_ascii=False, indent=2)
    p1_cfg_json = json.dumps(redact_secrets(stage1_cfg), ensure_ascii=False, indent=2)
    p2_cfg_json = json.dumps(redact_secrets(stage2_cfg), ensure_ascii=False, indent=2)
    p3_cfg_json = json.dumps(redact_secrets(stage3_cfg), ensure_ascii=False, indent=2)

    # progressive shrinking to avoid context explosions
    last_err: Optional[str] = None
    for shrink in [1.0, 0.7, 0.5, 0.35]:
        md_cap = int(80_000 * shrink)
        log_cap = int(140_000 * shrink)
        try:
            vars = {
                "dataset_name": ds_name,
                "final_output_dir": final_dir,
                "pipeline_summary_json": pipeline_summary_json,
                "phase1_config_json": p1_cfg_json,
                "experiment_config_json": exp_cfg_json,
                "review_config_json": review_cfg_json,
                "phase1_summary_md": read_text_limited(phase1_summary_path, max_chars=md_cap) if phase1_summary_path else "",
                "experiment_report_md": read_text_limited(experiment_report_path, max_chars=md_cap) if experiment_report_path else "",
                "review_report_md": read_text_limited(review_report_path, max_chars=md_cap) if review_report_path else "",
                "review_optim_history_md": read_text_limited(review_opt_hist_path, max_chars=md_cap) if review_opt_hist_path else "",
                "experiment_iters_json": json.dumps(exp_iters, ensure_ascii=False, indent=2),
                "review_iters_json": json.dumps(review_iters, ensure_ascii=False, indent=2),
                "pipeline_log_excerpt": read_head_tail_lines(pipeline_log_path, max_chars=log_cap),
                "experiment_log_excerpt": read_head_tail_lines(phase_logs.get("Experiment", ""), max_chars=log_cap),
                "review_log_excerpt": read_head_tail_lines(phase_logs.get("Review", ""), max_chars=log_cap),
            }

            user_prompt = user_template
            for k, v in vars.items():
                user_prompt = user_prompt.replace("${" + k + "}", str(v))

            report_md = chat_text(
                [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                llm_cfg,
            )

            if report_md:
                out_path = os.path.join(final_dir, "final_analysis_report.md")
                with open(out_path, "w", encoding="utf-8") as f:
                    f.write(report_md)
                return out_path
        except Exception as e:
            last_err = str(e)
            # If likely context error, continue shrinking; otherwise still retry smaller once.
            continue

    if last_err:
        print(f"[WARN] Final report generation failed: {last_err}")
    return None


# =============================================================================
# Runner-facing wrapper (backward compatibility)
# =============================================================================


def generate_final_report_and_exports(
    pipeline_summary: Dict[str, Any],
    stage_map: Dict[str, Dict[str, Any]],
    pipe_cfg: Optional[Dict[str, Any]] = None,
) -> Optional[str]:
    """Compatibility wrapper used by the unified runner.

    The original runners code invoked a higher-level helper that packaged configs,
    log paths, and explicit artifact locations. During refactor, the core report
    generator was separated into `generate_final_report(...)`.

    This wrapper reconstructs the same inputs without re-introducing Phase-1
    dependencies.
    """

    ds_name = str(pipeline_summary.get("dataset") or "")
    logs_dir = str(pipeline_summary.get("logs_dir") or "")
    results_root = os.path.join(project_root(), "results", ds_name) if ds_name else os.path.join(project_root(), "results")

    phase_logs = {
        "Experiment": os.path.join(logs_dir, "experiment.log") if logs_dir else "",
        "Review": os.path.join(logs_dir, "review.log") if logs_dir else "",
    }

    # Use Experiment log as the pipeline log anchor (runner does not create a separate pipeline log).
    pipeline_log_path = phase_logs.get("Experiment", "") or ""

    stage2_cfg = (stage_map.get("Experiment", {}) or {}).get("_loaded_cfg") or {}
    stage3_cfg = (stage_map.get("Review", {}) or {}).get("_loaded_cfg") or {}
    stage1_cfg: Dict[str, Any] = {}  # Phase 1 removed

    # Timings (best-effort)
    stage_timings = {}
    try:
        for k, v in (pipeline_summary.get("stages") or {}).items():
            if isinstance(v, dict):
                stage_timings[k] = {"time_sec": float(v.get("time_sec") or 0.0)}
    except Exception:
        stage_timings = {}

    # Explicit artifact directories (best-effort from logs)
    from .utils import extract_best_path_from_log

    explicit_experiment_path = None
    explicit_review_path = None

    try:
        # Experiment base dir
        exp_base = ((stage2_cfg.get("paths") or {}).get("design_execution_root")
                   or (stage2_cfg.get("prompt_branch") or {}).get("save_root")
                   or os.path.join("results", ds_name, "generate_execution"))
        exp_base = os.path.abspath(os.path.join(project_root(), exp_base)) if not os.path.isabs(str(exp_base)) else str(exp_base)
        explicit_experiment_path = extract_best_path_from_log(phase_logs["Experiment"], stage="Experiment", base_dir=exp_base, t_start=0.0)
    except Exception:
        explicit_experiment_path = None

    try:
        review_base = ((stage3_cfg.get("paths") or {}).get("review_feedback_root")
                   or os.path.join("results", ds_name, "review_feedback"))
        review_base = os.path.abspath(os.path.join(project_root(), review_base)) if not os.path.isabs(str(review_base)) else str(review_base)
        explicit_review_path = extract_best_path_from_log(phase_logs["Review"], stage="Review", base_dir=review_base, t_start=0.0)
    except Exception:
        explicit_review_path = None

    # Metric + direction
    metric = ((stage3_cfg.get("review") or {}).get("target_metric")
              or (stage2_cfg.get("experiment") or {}).get("primary_metric")
              or "PCC")
    direction = ((stage3_cfg.get("review") or {}).get("direction") or "maximize")

    return generate_final_report(
        ds_name=ds_name,
        results_root=results_root,
        pipeline_summary=pipeline_summary,
        stage1_cfg=stage1_cfg,
        stage2_cfg=stage2_cfg,
        stage3_cfg=stage3_cfg,
        stage_timings=stage_timings,
        phase_logs=phase_logs,
        pipeline_log_path=pipeline_log_path,
        pipe_cfg=pipe_cfg,
        explicit_experiment_path=explicit_experiment_path,
        explicit_review_path=explicit_review_path,
        direction=direction,
        metric=metric,
        output_dir=logs_dir if logs_dir else None,
    )